apiVersion: v1
kind: Service
metadata:
  name: meters-br-service
spec:
  type: ClusterIP
  selector:
    app: meters-br
  ports:
    - protocol: TCP
      port: 8080            # Service port (should match container port)
      targetPort: 8080      # Container port

