apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
spec:
  type: ClusterIP
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 1883          # MQTT default port
      targetPort: 1883

